### ISSUE TITLE
LowpassFourPole algorithm needs review

### ISSUE THREAD

**Issue by tap** [jamoma/jamoma2#12]
The following are concerns:
- The resonance provided by adjusting Q does not seem proportional to the values.
- Especially with non-low values of Q, the filter is incredibly unstable when changing the cutoff freq
- This code was written a long long time ago before I knew what I was doing, and has been copy/pasted ever since

**Comment by nwolek** [comment]
Original source of the algorithm appears to be here:
http://musicdsp.org/archive.php?classid=3#26

**Comment by nwolek** [comment]
I built an impulse response using the following code in Processing:

<pre>
double in1 = 0;
double in2 = 0;
double in3 = 0;
double in4 = 0;
double out1 = 0;
double out2 = 0;
double out3 = 0;
double out4 = 0;
void setup() {
  for (int i = 0; i < 64; i++)
  {
     double x, y;
    
      if (i==0) 
     {
        x = 1.0;
     } else {
        x = 0.0;
     }
     y = process(x, 0.5, 1.0);
     
     //println("x = " + x + " - y = " + y);
     println(x);
  }
}
double process(double input, double fc, double res)
{
  // source: http://musicdsp.org/archive.php?classid=3#26
  double f = fc * 1.16;
  double fb = res * (1.0 - 0.15 * f * f);
  input -= out4 * fb;
  input *= 0.35013 * (f*f)*(f*f);
  out1 = input + 0.3 * in1 + (1 - f) * out1; // Pole 1
  in1  = input;
  out2 = out1 + 0.3 * in2 + (1 - f) * out2;  // Pole 2
  in2  = out1;
  out3 = out2 + 0.3 * in3 + (1 - f) * out3;  // Pole 3
  in3  = out2;
  out4 = out3 + 0.3 * in4 + (1 - f) * out4;  // Pole 4
  in4  = out3;
  return out4;
}
</pre>

**Comment by tap** [comment]
It sounds plausible that the code came from there.  If we can confirm this the case we should document it as such.

If the IR is different then it must be either that we're doing something wrong or there is some floating-point round-off difference.  Would be nice to know a bit more about this...

**Comment by tap** [comment]
@nwolek To make things easier and give us a fuller set of tools for evaluating the correctness of this filter, I create a Max object to wrap it -- https://github.com/tap/TapTools/blob/master/source/tap.fourpole~/tap.fourpole~.cpp

To build:
- checkout TapTools (master branch)
- git submodule update --init
- find the tap.fourpole xcodeproj and build it

Maybe this will be helpful in this case.  If not, maybe it provides a useful model for making Max externs.

**Comment by tap** [comment]
@nwolek one additional note -- with the JUCE-based AU plug-in running in Live I can confirm the dramatic improvement in filter stability when changing cf and q.

**Comment by nwolek** [comment]
Did some more testing this morning. My procedure was to run <a href="https://github.com/jamoma/jamoma2/blob/master/examples/simple.cpp#L305">the simple.cpp test graph</a> in Xcode that produces filtered noise and then tune a cycle~ oscillator in Max to match the pitch I heard. I removed the 1.16 multiplier in <a href="https://github.com/jamoma/jamoma2/blob/master/includes/JamomaLowpassFourPole.h#L59">this line of code</a> and took turns setting it equal to radians and fNormalizedToNyquist for four frequency settings (500, 1000, 2000, & 4000). Here are my results:

<pre>
frequency   fNormalizedToNyquist    radians
500         340                     515
1000        680                     1068
2000        1360                    2295
4000        2760                    5403 ?
</pre>

My observations:
1. radians gets closer to the frequency settings as @tap noted, but it is non-linear
2. fNormalizedToNyquist appears to be linear, but is farther off the frequency setting

Recommended path forward:
_Using fNormalizedToNyquist with an adjusted multiplier (1.47058824 according to my math) should give us a stable and tunable filter._

**Comment by nwolek** [comment]
Seemed like a good theory. Results are sounding more non-linear in the application. Bummer.

**Comment by nwolek** [comment]
Found the Stilson/Smith paper here: https://ccrma.stanford.edu/~stilti/papers/moogvcf.pdf

To quote the conclusion: "Implementability issues make the conversion of the Moog VCF to a digital form nontrivial." Basically digital versions of this filter are either going to get good frequency control or resonance, but not both.

**Comment by nwolek** [comment]
Another source here on this filter: http://www.acoustics.ed.ac.uk/wp-content/uploads/AMT_MSc_FinalProjects/2012__Daly__AMT_MSc_FinalProject_MoogVCF.pdf

To quote the recommendations section: "The result of this report can be stated succinctly: it is possible to create a very accurate model of the Moog VCF but at considerable costs to either cut-off frequency range or input signal amplitude and computational expense. Any further investigations should not seek to improve the accuracy of the model but focus on the problems of stability and computational time."

It seems that others have tread down these waters before and found the same limitations in this filter design. The question for us is what to do about it. 

_Does this filter sound so good that we want to accept its limitations?_

**Comment by nwolek** [comment]
I have implemented a test for the current expected impulse response. If something changes, we will know about it.

**Comment by nwolek** [comment]
I think this has been reviewed and documented enough to close the issue.

**Comment by tap** [comment]
updated link for musicdsp source: http://musicdsp.org/showArchiveComment.php?ArchiveID=26
