### ISSUE TITLE
How do we organise header files as the number of files increase?

### ISSUE THREAD

**Issue by lossius** [jamoma/jamoma2#13]
Currently all files are in the same folder. As we add more stuff (Foundation, DSP units, AudioGraph, nodestuff, etc.) this will become a mayhem. How do we manage to tidy this up? Two possible solutions that I can think of:
- Organising files in subfolders in a somewhat similar fashion to Jamoma1 Core
- Longer and more detailed names for files. Personally I'm saceptic to this one, the name of files should reflect the class(es) they define.

**Comment by tap** [comment]
I'm going to invoke Agile at this point and call YAGNI on fragmenting into folders. My opinion is that we should stick with as flat a file organization as possible, and not convolute the names. The current folder hierarchy of Jamoma1 is confusing and cumbersome.

For structuring, I think it makes more sense to let the IDE do that if we want a different structure.  It is likely that the project at hand will suggest different structurings and therefore any structure we try to impose will be "wrong" some of the time.

The folder structure (if you can call it that) is then an alphabetical listing of everything, which is not automatic to obtain if Jamoma is fragmented into folders (or worse, folders of folders).  There are exceptions though.  Any place where we have a compound class then it could be put into a folder. The SpatLib and DataspaceLibs both come to mind here.

At any rate, if you simply `#include "jamoma.h"` then the only file that matters is this one and the others can be shuffled around without consequence at a latter date and time, so there is no pressure to get this "right" in the short term.

**Comment by nwolek** [comment]
I agree with staying flat for the time being. The simplicity of the include call is a good argument for this being good enough. Also, if we commit to getting Doxygen comments right from the start of this project, inheritance and organization can be explained there.

**Comment by tap** [comment]
With a question like this I'm unsure about the process for closing an open issue?  How do we know that this question has been adequately answered?

**Comment by nwolek** [comment]
I think it should be closed for now by virtue of the fact the 2/3 of contributors agree to remain flat for the time being. @lossius is free to raise the question again as things get bigger. Have the issue remain open and open-ended is not helpful. Therefore, I am closing it.
