### ISSUE TITLE
Symbol: stub class needs to be fleshed out

### ISSUE THREAD

**Issue by nwolek** [jamoma/jamoma2#15]
Looks like @tap wrote minimal code here to get something working. Needs more code before we have a working class here.

**Comment by tap** [comment]
Yes. I put some work into porting the Symbol over from Jamoma1 since it is one area of Jamoma1. 
In reflecting though I think maybe a different implementation might be wise.

Some random thoughts I've had:

### A Symbol is a string and an identifier

In Jamoma1 we also have a 2nd identifier for the table that owns it.
We probably want to keep this in case we have multiple pieces of code (like 2 plug-ins, or a host and a plug-in) both using Jamoma.

### If all Symbols were all shared-pointers, then the symbol table would be able to prune entries when a Symbol is no longer used.

 In Jamoma1 Symbols existed forever, which is sort of like a great big intentional memory leak.

### How do we instantiate the singleton symbol table instance?

This is a specialized variation of the question: **how do you create a global in a header-only environment?**

This is a very important question for us to answer.

**Comment by bltzr** [comment]
>  Needs more code before we have a working class here.

So, finally jamoma2 is a marxist project ;-)

**Comment by nwolek** [comment]
and started in the USA no less @bltzr ;)

**Comment by bltzr** [comment]
amazing !!!

**Comment by tap** [comment]
Marxism aside, I've done more reflecting on this issue of symbols and I wonder if the new architecture of Jamoma2 makes the need for a symbol table less relevant.

In what scenarios do we typically leverage the speed of the Symbol over the speed of a String?
- Sending a message, or attribute change, by name -- the receiving object has to compare the name sent in against a reference name.  With a symbol it compares 2 ints or it hashes a string.  With static linking in C++ in Jamoma2 you never do this.  A dynamic class wrapper would still do this, but the Max class wrapper as it exists is not using cached Symbols generally anyway -- see `filter_setFrequency()` in j.filter.cpp as an example. So we don't lose much...
- For lookup to create a new instance through the factory for new objects. currently this factory isn't implemented in Jamoma2.  Even if we do this, the creation of a new object is so expensive that it will dwarf the computational expense of a string comparison, especially a short string comparison.
- For setting an attribute whose data is a Symbol. E.g. the `mode` of an Overdrive object or the `name` of a file to read.

In the latter case the filename may or may not need a comparison to avoid reading an already loaded file, but who cares -- the expense of reading a file is so massive that it won't be noticed.

In the former case we are more likely to care.  Here is a specific scenario: A series of changes to the `mode` parameter for Overdrive are made. These are queued to be executed in the process method.  Now we have a whole series of string comparisons happening in the process method and the CPU usage potentially skyrockets.

So, in a world without a Symbol that compares quickly, what do we do?

**First**, for any calls made in C++ the idea of passing a string is questionable. It can't be autocompleted when writing the code. Documentation is not available when highlighting it in the IDE. It can't be type-checked at compile-time, meaning you don't know about errors until someone is running the code. And (as mentioned) it is slower than molasses.

An idiomatic solution in C++ would be to use enums for these parameters. Comparisons are then a single int, autocomplete, doc integration, and type-safety are all present.

But the enum won't be available in a more dynamic class-wrapper type of environment. So...

**Second**, any parameters that take these enums should also take strings which are converted to the enums.  

If we do this are there any hidden gotchas?

I'm unsure, but in most dynamic cases I'm thinking it will end up in a raw string at somepoint anyway -- data serialized from Max, or serialized from a webserver or OSC, etc.

At any rate, it's worth some thought.  And if we can eliminate the Symbol altogether then maybe it's a good thing?

Would be nice to get some feedback here from @theod @avilleret @jcelerier and @lossius

**Comment by jcelerier** [comment]
> How do we instantiate the singleton symbol table instance?
> This is a specialized variation of the question: how do you create a global in a header-only environment?

Some possibilites  : 

1 - Go full-blown on compile-time metaprogramming with libraries like Boost.Hana, Boost.Fusion, Boost.MPL that allows to create lists / maps of type.

It is still possible to "extend" a vector of list this way : http://www.boost.org/doc/libs/1_41_0/libs/mpl/doc/refmanual/vector.html, so for instance, there could be a symbol table defined in JamomaCore, another in JamomaDSP / some random extension and one could join them at compile time to craft the symbol table one wants to use in the software; it shouldn't be hard then to take this compile-time generated symbol list to instantiate a run-time one that could be modified afterwards if necessary, by having an init method somewhere.

2 - By using a static in an inline method. Guaranteed to be the same across all compilation units : 

```
enum symbols { symA, symB, symC };

inline map<symbols, string>& getSingletonMap()
{
    static map<symbols, string> theMap{
        {symA, "SymbolA"}, 
        {symB, "SymbolB"}, 
        {symC, "SymbolC"}
   }; 

    return theMap;
}
}; 
```

Here is a working example that features usage in two compilation units and modification of the map : http://s000.tinyupload.com/index.php?file_id=57808258444318625502

However I think that it will be shared between multiple shared objects/dylibs/DLLs only in Unix-like systems, not in Windows.

Also, something to keep in mind is that compile time hash functions are a thing :) (nothing prevents an usage at runtime though) e.g. https://gist.github.com/Teknoman117/d4d952942b4314781432 (but there are a lot of different implementations in the shady corners of stackoverflow). Don't know if it could be of some help... this could transform a lot of string comparisons into integer comparisons.

**Comment by tap** [comment]
Thanks @jcelerier !  I was looking for a way to do constexpr hashing this morning and getting a bit frustrated -- I should have read my emails first!

Also psyched about the option of using a static in an inline function.  I was not aware of how that was specified in the C++ standard.  For others who are curious, there is reference to the specific part of the C++ specification regarding this rule @ http://stackoverflow.com/questions/185624/static-variables-in-an-inlined-function
