### ISSUE TITLE
Overdrive: stub class needs to be fleshed out

### ISSUE THREAD

**Issue by nwolek** [jamoma/jamoma2#16]
Looks like @tap was copying code over from old codebase, but then commented out all of it.

**Comment by tap** [comment]
We have since discussed next steps in the roadmap, and this class is not part of that.  So we could continue with the porting of it, or we could just delete it for now until we are later ready to bring it in.

**Comment by nwolek** [comment]
I agree with your assessment. I am deleting it then. We can always revive later. Don't want to be distracted by stub classes and issues that are open for too long.
