### ISSUE TITLE
Design of Noise Generators

### ISSUE THREAD

**Issue by tap** [jamoma/jamoma2#18]
The Jamoma1 noise generator has a switch to select between different types of noise.

In Jamoma2 do we want to continue this way?  Or do we rather want to have specific classes for each type of noise (without the switch)?  If go with separate classes do we want a wrapper class like we use with the filters?

I think the answer is that last option, but I propose it here for review before taking action. Specifically wondering how @lossius would think about this design problem/pattern.

**Comment by nwolek** [comment]
I noticed this while writing documentation on the new JamomaNoise this morning. For now, we simply need the white noise but should consider this before more get implemented. I do think that the design pattern should be consistent between Filter and Noise.

**Comment by lossius** [comment]
My voice also goes towards implementing them as two separate classes. I'm not sure if we need a filter-like wrapper for them, I'd consider this to be two among many kinds of sound generators that we might implement, and it's just as likely that you want to switch between noise, sine and other waveforms as between different kinds of noise.

As we all seem to agree, I consider this a conclusion, and I'll close this issue
