### ISSUE TITLE
Create unit impulse AudioObject

### ISSUE THREAD

**Issue by nwolek** [jamoma/jamoma2#19]
https://en.wikipedia.org/wiki/Dirac_delta_function

Need this for testing filter responses. A lot of the necessary code is done as part of my testing the for issue #12. See the following section of code:

https://github.com/jamoma/jamoma2/blob/master/examples/simple.cpp#L93

**Comment by tap** [comment]
Interesting!  I did not know about the Dirac Function in this context.

Let me know if you need to talk about this at any point.

**Comment by nwolek** [comment]
working and passes test
