### ISSUE TITLE
Implement method for double comparison

### ISSUE THREAD

**Issue by nwolek** [jamoma/jamoma2#26]
We will need this immediately for testing the impulse responses of our filters. An example of where this is needed can be seen here:

https://github.com/jamoma/jamoma2/blob/master/examples/simple.cpp#L272

**Comment by tap** [comment]
The commit here is implemented somewhat generically (i.e. to work on both 32- and 64-bit values) but could likely be improved.

@nwolek please test and close it if you are happy -- example usage is in the new Dcblocker unit test.

**Comment by tap** [comment]
I'm happy with this now, so I'm closing it out.
