### ISSUE TITLE
Should LowpassFourPole "q" really be named "resonance"?

### ISSUE THREAD

**Issue by nwolek** [jamoma/jamoma2#27]
Most of the sources I reviewed for issue #12 called it resonance. It is not the same thing as Q, but I am having a hard time finding an online source that explains the difference/relationship clearly. Clearest thing was this discussion: https://www.native-instruments.com/forum/threads/filter-q-vs-resonance.234219/

The original Moog VCF panel has a resonance knob:
![Moog VCF panel](http://www.analog-monster.de/VCFModuleFront.jpg)

Just want to make sure @tap or others support renaming before I proceed.

**Comment by tap** [comment]
Please rename.  I have a recollection now that I renamed it from resonance to q for the j.filter~ object so that it could be controlled using the same attribute as the others.  But this was misleading and should never have been done.

Thanks, @nwolek !

**Comment by lossius** [comment]
In a thread at a NI forum, one of the NI techs gives the following conversion between resonance and quality:

1/Q=2(1-resonance)

https://www.native-instruments.com/forum/threads/filter-q-vs-resonance.234219/

**Comment by lossius** [comment]
(the previous post got posted prematurely, so if watching in mail, please check online)

**Comment by lossius** [comment]
The reason why we wanted all filters to have a Q parameter, was that they would share the same interface, and thus could be used interchangeably. But if a filter is a beast of a different colour I'd say that it does not make sense to force it to have a Q.
