### ISSUE TITLE
Dataspaces v2 Implementation

### ISSUE THREAD

**Issue by tap** [jamoma/jamoma2#29]
Implemented as templates that can be applied with configurability at runtime (like we do in Jamoma1) or hyper-efficiently at compile time.  Also to be passed as part of a Parameter definition.

**Comment by tap** [comment]
Next is integration with the Parameter class so that Parameters can have a Dataspace.

**Comment by tap** [comment]
I'm not 100% confident on how this is all done... A few spots definitely don't feel "elegant"...  But at least it works and we can (hopefully) review and revise later.

**Comment by lossius** [comment]
Eventually we should probably do a brainstorming session and look into how all of the services need to work together, in particular dataspace and ramping/easing (or LFO).

**Comment by tap** [comment]
I agree.  It was at least obvious that dataspace conversion needs to be applied prior to clipping, but then ramping/easing adds a whole new challenge and I know this was carefully specified in Jamoma1.
