### ISSUE TITLE
Unit Testing: Implement / Integrate initial structure and tests

### ISSUE THREAD

**Issue by tap** [jamoma/jamoma2#4]

**Comment by nwolek** [comment]
What would be the steps to closing this issue?

**Comment by tap** [comment]
Something is in place -- now we just need to start moving code out of the example program and into individual unit test programs.

**Comment by tap** [comment]
@nwolek When you have some moments to carve away... Would you be willing to take a look at (build and run) the project in `tests/Dcblocker` ?

**Comment by nwolek** [comment]
I just opened the project and it builds and runs here. No warnings, so I think it was successful.Where do the logs go? Without them, it feels like there is very little feedback to the user/developer.

**Comment by tap** [comment]
This one doesn't fail any more because I changed the reference impulse response used for comparisons.

A few ways to see the results:
- In Xcode, in the JamomaTest_Dcblocker project, `build and run` the "UnitTest" target
- In Xcode, in the JamomaTest_Dcblocker project, `build` the "UnitTest-Make" target (failures will show up as errors)
- On the command line, run `make test` in the Dcblocker folder or at the top level (to run all tests)
- In a web browser you can see the CI build that was triggered the last time someone pushed a commit @ https://travis-ci.org/jamoma/jamoma2
