### ISSUE TITLE
Interpolation Classes

### ISSUE THREAD

**Issue by tap** [jamoma/jamoma2#56]
In the design of interpolation classes, the class should include a query-able constant that defines the number of samples required to perform said interpolation.

This is in addition to the obvious algorithm and potential member vars.

**Comment by tap** [comment]
We also need to consider #43 in the implementation of the interpolation classes -- though I don't really understand the underlying concern of that issue very well.  Likely need to have a conversation with @nwolek to iron this out.

**Comment by tap** [comment]
Hi Nathan -- I did the initial port from Jamoma1 (see commit above).  A couple of the interpolation types are not currently tested.  Also I didn't scrutinize the comments and it could use review as well.

In Jamoma1 these were implemented as templated _functions_.  For Jamoma2 I have implemented them as templated _classes_.  

Because classes have the function operator defined, they can be called as functions.  However, they can also have state now (see the Hermite interpolation) and you pass instances of the interpolation around.  Also, since it is a class, you can also use it's type to specialize template -- which I've demonstrated in the unit tests.

**Comment by nwolek** [comment]
OK, thanks Tim. I was trying to make some progress on #35 today, but will give this an initial look today too. I feel like both are going to be necessary for #41 where I need a modulating allpass filter.

**Comment by nwolek** [comment]
Looked at these again today. It took me a while to figure out how the test was working because of the template function and such. I am not sure we want our tests to be so obtuse. I am going to work toward simplification so that the code is more readable. That might mean violating the DRY principle in testing, but it will help the code serve as examples for others.

**Comment by nwolek** [comment]
Bookmarking these. Likely source of my targets for testing:

https://www.gnu.org/software/octave/doc/interpreter/One_002ddimensional-Interpolation.html

**Comment by nwolek** [comment]
Tests show pretty definitively that our algorithms for Hermite and Spline are not producing the same results as those from the similar named options for the Octave interp1 function. I will need to some more research on the source of these algorithms.

I found a few hits here: http://musicdsp.org/archive.php?classid=5

@tap did you have a common source for these interpolation algorithms initially?

**Comment by tap** [comment]
If you export code from gen~ and then look at the exported code I think you
will find something comparable.

best,
  Tim

**Comment by nwolek** [comment]
Found examples for linear, cosine, cubic, spline and hermite in the gen~.interpolation example. Working to migrate into Octave.

**Comment by nwolek** [comment]
Some simple explanations and code examples for [interpolation methods here](http://paulbourke.net/miscellaneous/interpolation/).

Two observations from today's testing:
1) Our [cubic](https://github.com/jamoma/jamoma2/blob/master/include/core/JamomaInterpolate.h#L117) and [spline](https://github.com/jamoma/jamoma2/blob/master/include/core/JamomaInterpolate.h#L139) algorithms produce identical output. Looking at the code shows why. I plan to fix this.
2) Setting the bias and tension settings both to zero results in identical output from spline and hermite. This should be documented.

**Comment by tap** [comment]
Thanks for all your work on this Nathan!  It's great that we are applying this level of rigor to the stuff we bring over from Jamoma1.  In the process we are definitively improving things!

That's a great interpolation article too -- thanks for including it here!

**Comment by nwolek** [comment]
Thanks Tim! I am glad you appreciate the work that went into this code review. I have merged it back into master now, and am calling this issue done. Feel free to re-open if you think I missed something.
