### ISSUE TITLE
Implement additional fill() options for SampleBundle

### ISSUE THREAD

**Issue by nwolek** [jamoma/jamoma2#68]
Found in code for `Jamoma::Sample`:

```
//TODO: Add some additional fill() options -- e.g. filling with a sine function, sinc function, etc.
//These can emulate options found here:
//https://github.com/jamoma/JamomaCore/blob/master/DSP/library/source/TTSampleMatrix.cpp#L254
```

Would seem to be a prerequisite to implementing a Wavetable object (issue #5).

Some of the recent discussion about interpolation may impact the way this is designed (issue #43). i.e. If we decide that interpolation should be outside the data container, does that mean the same thing for fill operations?

**Comment by tap** [comment]
Good question.  Makes my head hurt a little.  I'm thinking I may have stepped into an old trap/habit of mine where I let "perfect" be the enemy of "good".  But this is incremental development: we can always do something and then change it if reality dictates...

So in both this case and the interpolation case, I would say that if there is motivation to pursue one direction or the other that we should just do it.  Then we can evaluate something in concrete terms, and refactoring (if needed at all) will be easier with something legit from which to start.

**Comment by tap** [comment]
That said, I'm attracted to the idea that we could fill a std::vector or a CircularBuffer or a SampleVector or a SampleBundle or std::array each with e.g. a cosine wave using the same algorithm.  YMMV

**Comment by nwolek** [comment]
I am actually investigating this very thing by leveraging [std::generate](http://www.cplusplus.com/reference/algorithm/generate/). Whatever I do, I will keep in a branch for you to review and comment.

**Comment by tap** [comment]
Perfect!

**Comment by nwolek** [comment]
@tap - Please take a look at the work so far on branch `issue/68`. This is showing a lot of promise in my initial tests! A couple of questions I have for you:
-  I imagine our current [JamomaInterpolate](https://github.com/jamoma/jamoma2/blob/master/include/core/JamomaInterpolate.h) class provides a model for how to gather and structure this. If we collect these together into a separate file, do you have a preference for naming? I have been calling them FillFunctions in my comments, but they work with the `std::generate` function. "fill" and "generate" seem to be key terms.
- Trying to turn these into template classes that work with any datatype was a little tricky. Right now they only produce output as `Sample`. If you have any insight into the right syntax for this, please let me know. 
- Are there any other suggestions to make the syntax clearer? (renaming variables, etc)

**Comment by tap** [comment]
Working on the review right now.  Being a little picky.  Some of my questions might sound rhetorical but they are not.  For example, the struct vs class question.

I completely agree that we should not use "fill" terminology but instead "generate" terminology so that we are in alignment with the STL standard.

**Comment by tap** [comment]
It ended-up being easier to express myself in code than in comments about code.  Hopefully I haven't over-stepped!

**Comment by nwolek** [comment]
Nope. It looks like you pushed things forward in exactly the places I was stuck! Thanks!!! 

Talk to you in the morning.

**Comment by nwolek** [comment]
List of algorithms we had in Jamoma1's [SampleMatrix](https://github.com/jamoma/JamomaCore/blob/master/DSP/library/source/TTSampleMatrix.cpp#L254):
- [ ] triangleMod
- [x] triangle
- [ ] sawtoothMod
- [ ] sawtooth
- [ ] rampMod
- [x] ramp
- [ ] cosineMod
- [ ] cosine
- [ ] sineMod
- [x] sine

In this case, "Mod" really means [unipolar](http://www.encyclopedia.com/doc/1O11-unipolarsignal.html). I know this term is used in Roads CMT, therefore I would suggest we adopt this term.

**Comment by tap** [comment]
Another reference here are the fill/apply methods for the buffer~ object.  Specifically I'm thinking of the `sinc` function and also of only generating half of the wave.

Perhaps we should think of unipolar and generating half the wave as well as the frequency as attributes/parameters of the generators?

**Comment by nwolek** [comment]
This work is migrating to [JamomaGenerator.h](https://github.com/jamoma/jamoma2/blob/issue/68/include/core/JamomaGenerator.h)

**Comment by nwolek** [comment]
All shapes from SampleMatrix now implemented. Opening new issues for remaining shapes discussed with @tap.
