### ISSUE TITLE
Port position dataspace

### ISSUE THREAD

**Issue by lossius** [jamoma/jamoma2#96]

**Comment by lossius** [comment]
Hi @tap ,

I've now started implementing the position dataspace on the feature/96-position-dataspace branch. I've only added two units so far, but it's enough to reveal the stuff that we need to get ironed out before continuing.
- Cartesian3D dataspace has 3 dimensions: xyz
- Cartesian2D dataspace has 2 dimensions: xy (as z is always 0)

This implies that:
- a conversion from cart2D needs 2 values as input, and returns 3
- a conversion from neutral to cart2D needs 3 values as input, and returns 2

Can you please take a look and see what needs to be done in order for this to compile? When done, please make a pull request for merging this back into the feature/dataspace branch (not master) and assign to me, and I'll keep working on it in order to implement the remaining units, as well as setting up unit tests.

Thanks!

**Comment by tap** [comment]
@lossius -- I don't see this branch.  Is it pushed to Github?

**Comment by tap** [comment]
Hi @lossius -- please take a look at the above commit and tell me what you think...

**Comment by lossius** [comment]
Thanks, will check out tomorrow.

**Comment by lossius** [comment]
Thanks @tap this works. Brilliant! I'll see if I can finish of the dataspace by the end of the year then.

**Comment by lossius** [comment]
Closing this issue, one new issue showed up in the process, and is logged as #102 .

It remains to make an example of position dataspace conversions that illustrates how to vary the length of the returned vector based on what unit is used. The dataspace unit tests doesn't illustrate this.
